### PR TITLE
Allow Laravel 7

### PR DESCRIPTION
**Pull request by filipac**
Just release today :)

### CODE REVIEW

**Comment by shanmuga3** [comment]
Waiting for merge

**Comment by princeteck** [comment]
where can we expect this done?

**Comment by ichtrojan** [comment]
Please merge this

**Comment by Nyariki** [comment]
Please merge

**Comment by bornemisza** [comment]
@brozot Will you merge it into master?

**Comment by shalawani** [comment]
@brozot may you merge it, Please?

**Comment by jaimyborgman** [comment]
@brozot please merge this one

**Comment by williamdes** [comment]
:ping_pong:

**Review by AhmedNourJamalElDin — APPROVED** [review]

**Comment by ichtrojan** [comment]
Finally

**Comment by jaimyborgman** [comment]
the waiting continues 🤣  would be nice if this one would be merged asap 👍

**Comment by gioramies** [comment]
Waiting for merge. Getting closer.

**Comment by AhmedNourJamalElDin** [comment]
I am jusy a guy like you, guys.
Everyone has the permission to review any PR. 🤣

**Comment by AhmedNourJamalElDin** [comment]
Hi @brozot, do you need any help in this repository?

**Comment by ayberkcal** [comment]
@brozot ?

**Comment by kasperhartwich** [comment]
@brozot Please take a look at this!

**Comment by williamdes** [comment]
Hi !
Feel free to re-open this pull-request to [code-lts/Laravel-FCM](https://github.com/code-lts/Laravel-FCM#readme) if necessary (1.4.0 supports Laravel 7)

This is a fork that will be maintained as long as possible by @code-lts members :muscle: 

:rocket: 1.4.0 was released [See how to install it](https://github.com/code-lts/Laravel-FCM/tree/1.4.0#installation) (`composer require code-lts/laravel-fcm`)

**Comment by HasanAlyazidi** [comment]
Thank you @williamdes

Is `code-lts/laravel-fcm` temporary until `brozot/Laravel-FCM` supports Laravel 7+?

**Comment by williamdes** [comment]
> Thank you @williamdes
> 
> Is `code-lts/laravel-fcm` temporary until `brozot/Laravel-FCM` supports Laravel 7+?

I do not intend to close my fork unless the maintainer wants to merge all my work :)
This seem very unlikely, I would accept that @brozot transfers his repository to @code-lts

**Comment by alr2413** [comment]
Ping @brozot.

**Comment by shirkerohit** [comment]
Any update on this? @brozot ?

**Comment by ichtrojan** [comment]
@filipac @brozot this is still valid

**Comment by williamdes** [comment]
Next release I will support Laravel 8
https://github.com/brozot/Laravel-FCM/pull/174#issuecomment-669831236

**Pull request closed without merging**
